name: Check for Jira issue
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  jira_issue:
    runs-on: ubuntu-latest
    name: 'Jira issue key'
    steps:
      - name: 'Check PR title, body and branch name'
        uses: actions-ecosystem/action-regex-match@v2
        id: regex_match
        with:
          text: ${{ github.event.pull_request.title }} ${{ github.event.pull_request.body }} ${{ github.event.pull_request.head.ref }}
          regex: '${{ vars.JIRA_KEY_PREFIX }}-\d+'
          flags: gm

      - name: 'Fail'
        uses: actions/github-script@v3
        if: ${{ steps.regex_match.outputs.match == ''}}
        with:
          script: |
            core.setFailed('No Jira issue found in title, body, branch or commits, e.x: ${{ vars.JIRA_KEY_PREFIX }}-123!')
