name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true

      - name: Get PR info
        id: get_pr_info
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: 'Search Jira issue in PR title, body and branch name'
        uses: actions-ecosystem/action-regex-match@v2
        id: regex_match
        with:
          text: ${{ steps.get_pr_info.outputs.title }} ${{ steps.get_pr_info.outputs.body }}
          regex: '${{ vars.JIRA_KEY_PREFIX }}-\d+'
          flags: gm

      - uses: levigo/github-action-jira-fixversion@v1.0
        with:
          domain: ${{ secrets.JIRA_DOMAIN }}
          username: ${{ secrets.JIRA_USERNAME }}
          password: ${{ secrets.JIRA_TOKEN }}
          versionName: ${{ steps.tag_version.outputs.new_tag }}
          versionDescription: ${{ steps.get_pr_info.outputs.title }} ${{ steps.get_pr_info.outputs.body }}
          issueKeys: ${{ steps.regex_match.outputs.match || vars.JIRA_DEFUALT_ISSUE }}
